san_news_homepage:
    path:     /newse/{page}
    defaults: { _controller: SanNewsBundle:News:index }

san_news_view:
    path: /news/{id}
    defaults:
        _controller: SanNewsBundle:News:view
    requirements:
        id: \d+
        
san_news_add:
    path: /news/add
    defaults:
        _controller: SanNewsBundle:News:add
        
san_news_edit:
    path: /news/edit/{id}
    defaults:
        _controller: SanNewsBundle:News:edit
    requirements:
        id: \d+
        
san_news_delete:
    path: /news/delete/{id}
    defaults:
        _controller: SanNewsBundle:News:delete
    requirements:
        id: \d+
