san_news_homepage:
    path:     /admin/newse/{page}
    defaults:
        _controller: SanNewsBundle:News:index
        page: 1
    requirements:
        page: \d*

san_news_view:
    path: /admin/news/{id}
    defaults:
        _controller: SanNewsBundle:News:view
    requirements:
        id: \d+
        
san_news_add:
    path: /admin/news/add
    defaults:
        _controller: SanNewsBundle:News:add
        
san_news_edit:
    path: /admin/news/edit/{id}
    defaults:
        _controller: SanNewsBundle:News:edit
    requirements:
        id: \d+
        
san_news_delete:
    path: /admin/news/delete/{id}
    defaults:
        _controller: SanNewsBundle:News:delete
    requirements:
        id: \d+

san_news_categories:
    path: /admin/news/categories
    defaults:
        _controller: SanNewsBundle:News:categories
    