san_news_homepage:
    path:     /admin/newse/{page}
    defaults:
        _controller: SanNewsBundle:News:index
        page: 1
    requirements:
        page: \d*
        
san_news_page:
    path:     /news/{page}
    defaults:
        _controller: SanNewsBundle:News:pagenews
        page: 1
    requirements:
        page: \d* 
        
san_catnews_page:
    path:     /catnews/{cat}-{page}
    defaults:
        _controller: SanNewsBundle:News:catnews
        page: 1
        cat: 1
    requirements:
        page: \d*         

san_news_view:
    path: /admin/news/{id}
    defaults:
        _controller: SanNewsBundle:News:view
    requirements:
        id: \d+
        
san_newssolo_view:
    path: /newssolo/{id}
    defaults:
        _controller: SanNewsBundle:News:viewsolo
    requirements:
        id: \d+        
        
san_news_add:
    path: /admin/news/add
    defaults:
        _controller: SanNewsBundle:News:add
        
san_news_edit:
    path: /admin/news/edit/{id}
    defaults:
        _controller: SanNewsBundle:News:edit
    requirements:
        id: \d+
        
san_news_delete:
    path: /admin/news/delete/{id}
    defaults:
        _controller: SanNewsBundle:News:delete
    requirements:
        id: \d+

san_newscat_homepage:
    path: /admin/newscat/{page}
    defaults:
        _controller: SanNewsBundle:Newscat:index
        page: 1
    requirements:
        page: \d*
        
san_newscat_add:
    path: /admin/newscat/add
    defaults:
        _controller: SanNewsBundle:Newscat:add
        
san_newscat_edit:
    path: /admin/newscat/edit/{id}
    defaults:
        _controller: SanNewsBundle:Newscat:edit
    requirements:
        id: \d+
        
san_newscat_delete:
    path: /admin/newscat/delete/{id}
    defaults:
        _controller: SanNewsBundle:Newscat:delete
    requirements:
        id: \d+    