san_event_homepage:
    path:     /admin/events/{page}
    defaults:
        _controller: SanEventBundle:Event:index
        page: 1
    requirements:
        page: \d*

san_event_view:
    path: /admin/event/{id}
    defaults:
        _controller: SanEventBundle:Event:view
    requirements:
        id: \d+
            
san_event_add:
    path: /admin/event/add
    defaults:
        _controller: SanEventBundle:Event:add
        
san_event_edit:
    path: /admin/event/edit/{id}
    defaults:
        _controller: SanEventBundle:Event:edit
    requirements:
        id: \d+
        
san_event_delete:
    path: /admin/event/delete/{id}
    defaults:
        _controller: SanEventBundle:Event:delete
    requirements:
        id: \d+
        
san_insc_homepage:
    path:     /admin/inscriptions/{page}
    defaults:
        _controller: SanEventBundle:InscriptionEvent:index
        page: 1
    requirements:
        page: \d*

san_insc_view:
    path: /inscription/{id}
    defaults:
        _controller: SanEventBundle:InscriptionEvent:view
    requirements:
        id: \d+
        
san_insc_add:
    path: /inscription/add/{id}
    defaults:
        _controller: SanEventBundle:InscriptionEvent:add
    requirements:
        id: \d+   
        
san_insc_edit:
    path: /admin/inscription/edit/{id}
    defaults:
        _controller: SanEventBundle:InscriptionEvent:edit
    requirements:
        id: \d+
        
san_insc_delete:
    path: /admin/inscription/delete/{id}
    defaults:
        _controller: SanEventBundle:InscriptionEvent:delete
    requirements:
        id: \d+    
        
san_insc_deletepub:
    path: /inscription/delete/{id}
    defaults:
        _controller: SanEventBundle:InscriptionEvent:deletepub
    requirements:
        id: \d+           