san_event_homepage:
    path:     /admin/events/{page}
    defaults:
        _controller: SanEventBundle:Event:index
        page: 1
    requirements:
        page: \d*

san_event_view:
    path: /admin/event/{id}
    defaults:
        _controller: SanEventBundle:Event:view
    requirements:
        id: \d+
            
san_event_add:
    path: /admin/event/add
    defaults:
        _controller: SanEventBundle:Event:add
        
san_event_edit:
    path: /admin/event/edit/{id}
    defaults:
        _controller: SanEventBundle:Event:edit
    requirements:
        id: \d+
        
san_event_delete:
    path: /admin/event/delete/{id}
    defaults:
        _controller: SanEventBundle:Event:delete
    requirements:
        id: \d+