san_user_homepage:
    path:     /user
    defaults: { _controller: SanUserBundle:User:index }

san_user_view:
    path: /user/{id}
    defaults:
        _controller: SanUserBundle:User:view
    requirements:
        id: \d+
        
san_user_add:
    path: /user/add
    defaults:
        _controller: SanUserBundle:User:add
        
san_user_edit:
    path: /user/edit/{id}
    defaults:
        _controller: SanUserBundle:User:edit
    requirements:
        id: \d+
        
san_user_delete:
    path: /user/delete/{id}
    defaults:
        _controller: SanUserBundle:User:delete
    requirements:
        id: \d+