san_user_homepage:
    path:     admin/users/{page}
    defaults:
        _controller: SanUserBundle:User:list
        page: 1
    requirements:
        page: \d*

san_user_view:
    path: /admin/user/{id}
    defaults:
        _controller: SanUserBundle:User:view
    requirements:
        id: \d+

san_user_admin:
    path: /admin/useri/{id}
    defaults:
        _controller: SanUserBundle:User:admin
    requirements:
        id: \d+
        
                
san_user_add:
    path: /admin/user/add
    defaults:
        _controller: SanUserBundle:User:add
        
san_user_edit:
    path: /admin/user/edit/{id}
    defaults:
        _controller: SanUserBundle:User:edit
    requirements:
        id: \d+

san_rdv_edit:
    path: /admin/candidats/rdvedit/{id}
    defaults:
        _controller: SanUserBundle:User:rdvedit
    requirements:
        id: \d+             
   
san_user_delete:
    path: /admin/user/delete/{id}
    defaults:
        _controller: SanUserBundle:User:delete
    requirements:
        id: \d+
        
san_user_profil:
    path: /profil
    defaults:
        _controller: SanUserBundle:User:profil  
        
san_user_modprofil:
    path: /profil/edit
    defaults:
        _controller: SanUserBundle:User:modprofil  
        
san_user_delprofil:
    path: /profil/delete
    defaults:
        _controller: SanUserBundle:User:delprofil 
  
san_abonnes_homepage:
    path:     admin/abonnes/{page}
    defaults:
        _controller: SanUserBundle:Abonnement:index
        page: 1
    requirements:
        page: \d*        
              
san_abonnes_edit:
    path: /abonnes/edit/{id}
    defaults:
        _controller: SanUserBundle:Abonnement:edit
    requirements:
        id: \d+        
        
san_abonnes_delete:
    path: /abonnes/delete/{id}
    defaults:
        _controller: SanUserBundle:Abonnement:delete
    requirements:
        id: \d+       
        
san_statuts_homepage:
    path:     /admin/statuts/{page}
    defaults:
        _controller: SanUserBundle:Statut:index
        page: 1
    requirements:
        page: \d*
   
san_statuts_add:
    path: /admin/statuts/add
    defaults:
        _controller: SanUserBundle:Statut:add
        
san_statuts_edit:
    path: /admin/statuts/edit/{id}
    defaults:
        _controller: SanUserBundle:Statut:edit
    requirements:
        id: \d+
        
san_statuts_delete:
    path: /admin/statuts/delete/{id}
    defaults:
        _controller: SanUserBundle:Statut:delete
    requirements:
        id: \d+    


