san_user_homepage:
    path:     admin/users/{page}
    defaults:
        _controller: SanUserBundle:User:list
        page: 1
    requirements:
        page: \d*
        
san_user_view:
    path: /user/{id}
    defaults:
        _controller: SanUserBundle:User:view
    requirements:
        id: \d+
        
san_user_add:
    path: /user/add
    defaults:
        _controller: SanUserBundle:User:add
        
san_user_edit:
    path: /user/edit/{id}
    defaults:
        _controller: SanUserBundle:User:edit
    requirements:
        id: \d+
        
san_user_admin:
    path: /user/convert/{id}
    defaults:
        _controller: SanUserBundle:User:admin
    requirements:
        id: \d+        
        
san_user_delete:
    path: /user/delete/{id}
    defaults:
        _controller: SanUserBundle:User:delete
    requirements:
        id: \d+
        
san_user_profil:
    path: /profil
    defaults:
        _controller: SanUserBundle:User:profil        

san_abonnes_homepage:
    path:     admin/abonnes/{page}
    defaults:
        _controller: SanUserBundle:Abonnement:index
        page: 1
    requirements:
        page: \d*        
              
san_abonnes_edit:
    path: /abonnes/edit/{id}
    defaults:
        _controller: SanUserBundle:Abonnement:edit
    requirements:
        id: \d+        
        
san_abonnes_delete:
    path: /abonnes/delete/{id}
    defaults:
        _controller: SanUserBundle:Abonnement:delete
    requirements:
        id: \d+        