<?php

namespace San\OffresBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;
/**
 * CandidatureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CandidatureRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCand($id)
  {
     $query = $this->createQueryBuilder('a')
      ->innerJoin('a.offre', 'c')
      ->addSelect('c')
    ;
      $query->setMaxResults(1);
return $query
    ->getQuery()
    ->getOneorNullResult()
  ;
  }   
}
