<?php

namespace San\NewsBundle\Repository;

/**
 * newscatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class newscatRepository extends \Doctrine\ORM\EntityRepository
{
}
