<?php

namespace San\EventBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;
/**
 * InscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InscriptionRepository extends \Doctrine\ORM\EntityRepository
{
      public function getInscriptions($page, $nbPerPage)
  {
     $query = $this->createQueryBuilder('a')
      ->leftJoin('a.event', 'c')
      ->addSelect('c')
      ->orderBy('a.pubDate', 'DESC')
      ->getQuery()
    ;

     $query
      // On définit l'annonce à partir de laquelle commencer la liste
      ->setFirstResult(($page-1) * $nbPerPage)
      // Ainsi que le nombre d'annonce à afficher sur une page
      ->setMaxResults($nbPerPage)
    ;

    // Enfin, on retourne l'objet Paginator correspondant à la requête construite
    // (n'oubliez pas le use correspondant en début de fichier)
    return new Paginator($query, true);
   
  }
  
     public function getInsc($id)
  {
     $query = $this->createQueryBuilder('a')
      ->innerJoin('a.event', 'c')
      ->addSelect('c')
    ;
      $query->setMaxResults(1);
return $query
    ->getQuery()
    ->getOneorNullResult()
  ;
  }
}
