san_core_homepage:
    path:     /index
    defaults: { _controller: SanCoreBundle:Core:index }
    
san_vue_offre:
    path:     /vueoffre
    defaults: { _controller: SanCoreBundle:Core:vueoffre }    
