san_core_homepage:
    path:     /index
    defaults: { _controller: SanCoreBundle:Core:index }
    
san_carriere_homepage:
    path:     /carriere
    defaults: { _controller: SanCoreBundle:Core:carriere }

san_conseil_homepage:
    path:     /conseil
    defaults: { _controller: SanCoreBundle:Core:conseil }
    
san_services_homepage:
    path:     /services
    defaults: { _controller: SanCoreBundle:Core:services }
    
san_solutions_homepage:
    path:     /solutions
    defaults: { _controller: SanCoreBundle:Core:solutions }
    
san_legal_homepage:
    path:     /legal
    defaults: { _controller: SanCoreBundle:Core:legal }    
    
san_vue_offre:
    path:     /vueoffre
    defaults: { _controller: SanCoreBundle:Core:vueoffre }    

san_core_test:
    path:     /test
    defaults: { _controller: SanCoreBundle:Core:sendmail } 
    
san_core_contact:
    path:     /contact
    defaults: { _controller: SanCoreBundle:Core:contact }