san_offre_homepage:
    path:     /admin/offres/{page}
    defaults:
        _controller: SanOffresBundle:Offre:index
        page: 1
    requirements:
        page: \d*

san_offre_view:
    path: /admin/offre/{id}
    defaults:
        _controller: SanOffresBundle:Offre:view
    requirements:
        id: \d+
        
san_offre_add:
    path: /admin/offre/add
    defaults:
        _controller: SanOffresBundle:Offre:add
        
san_offre_edit:
    path: /admin/offre/edit/{id}
    defaults:
        _controller: SanOffresBundle:Offre:edit
    requirements:
        id: \d+
        
san_offre_delete:
    path: /admin/offre/delete/{id}
    defaults:
        _controller: SanOffresBundle:Offre:delete
    requirements:
        id: \d+