san_offre_homepage:
    path:     /admin/offres/{page}
    defaults:
        _controller: SanOffresBundle:Offre:index
        page: 1
    requirements:
        page: \d*

san_offre_view:
    path: /admin/offre/{id}
    defaults:
        _controller: SanOffresBundle:Offre:view
    requirements:
        id: \d+
        
san_offre_offre:
    path: /carriere/offre/{id}
    defaults:
        _controller: SanOffresBundle:Offre:offre
    requirements:
        id: \d+        
        
san_offre_add:
    path: /admin/offre/add
    defaults:
        _controller: SanOffresBundle:Offre:add
        
san_offre_edit:
    path: /admin/offre/edit/{id}
    defaults:
        _controller: SanOffresBundle:Offre:edit
    requirements:
        id: \d+
        
san_offre_delete:
    path: /admin/offre/delete/{id}
    defaults:
        _controller: SanOffresBundle:Offre:delete
    requirements:
        id: \d+
        
san_candidature_homepage:
    path:     /carriere/candidature/{page}
    defaults:
        _controller: SanOffresBundle:Candidature:index
        page: 1
    requirements:
        page: \d*
        
san_candidature_add:
    path: /carriere/candidature/add/{id}
    defaults:
        _controller: SanOffresBundle:Candidature:add
    requirements:
        id: \d+  
        
san_candidature_succes:
    path: /carriere/candidature/succes/{id}
    defaults:
        _controller: SanOffresBundle:Candidature:succes
    requirements:
        id: \d+
        
san_candidature_view:
    path: /carriere/candidature/view/{id}
    defaults:
        _controller: SanOffresBundle:Candidature:view
    requirements:
        id: \d+        
        
san_candidature_edit:
    path: /carriere/candidature/edit/{id}
    defaults:
        _controller: SanOffresBundle:Candidature:edit
    requirements:
        id: \d+
        
san_candidats_edit:
    path: /admin/candidats/edit/{id}
    defaults:
        _controller: SanOffresBundle:Candidature:adminedit
    requirements:
        id: \d+        
        
san_candidature_delete:
    path: /carriere/candidature/delete/{id}
    defaults:
        _controller: SanOffresBundle:Candidature:delete
    requirements:
        id: \d+
        
san_candidats_liste:
    path:     /admin/candidats/{page}
    defaults:
        _controller: SanOffresBundle:Candidature:index
        page: 1
    requirements:
        page: \d* 
        
san_cvtheque_homepage:
    path:     /admin/cvtheque/{page}
    defaults:
        _controller: SanOffresBundle:Candidature:cvtheque
        page: 1
    requirements:
        page: \d*         
        
san_candidats_statutlist:
    path: /admin/candidats/statut/{id}
    defaults:
        _controller: SanOffresBundle:Candidature:statutlist
    requirements:
        id: \d+  
        
san_candidats_view:
    path: /admin/candidat/{id}
    defaults:
        _controller: SanOffresBundle:Candidature:adminview
    requirements:
        id: \d+  
        
san_candidats_pdf:
    path: /admin/candidat/pdf/{id}
    defaults:
        _controller: SanOffresBundle:Candidature:toPdf
    requirements:
        id: \d+          
        
san_categories_homepage:
    path:     /admin/categories/{page}
    defaults:
        _controller: SanOffresBundle:Categorie:index
        page: 1
    requirements:
        page: \d*
   
san_categories_add:
    path: /admin/categories/add
    defaults:
        _controller: SanOffresBundle:Categorie:add
        
san_categories_edit:
    path: /admin/categories/edit/{id}
    defaults:
        _controller: SanOffresBundle:Categorie:edit
    requirements:
        id: \d+
        
san_categories_delete:
    path: /admin/categories/delete/{id}
    defaults:
        _controller: SanOffresBundle:Categorie:delete
    requirements:
        id: \d+  
        
san_competences_homepage:
    path:     /admin/competences/{page}
    defaults:
        _controller: SanOffresBundle:Competence:index
        page: 1
    requirements:
        page: \d*
   
san_competences_add:
    path: /admin/competences/add
    defaults:
        _controller: SanOffresBundle:Competence:add
        
san_competences_edit:
    path: /admin/competences/edit/{id}
    defaults:
        _controller: SanOffresBundle:Competence:edit
    requirements:
        id: \d+
        
san_competences_delete:
    path: /admin/competences/delete/{id}
    defaults:
        _controller: SanOffresBundle:Competence:delete
    requirements:
        id: \d+         
        
san_contrats_homepage:
    path:     /admin/contrats/{page}
    defaults:
        _controller: SanOffresBundle:Contrat:index
        page: 1
    requirements:
        page: \d*
   
san_contrats_add:
    path: /admin/contrats/add
    defaults:
        _controller: SanOffresBundle:Contrat:add
        
san_contrats_edit:
    path: /admin/contrats/edit/{id}
    defaults:
        _controller: SanOffresBundle:Contrat:edit
    requirements:
        id: \d+
        
san_contrats_delete:
    path: /admin/contrats/delete/{id}
    defaults:
        _controller: SanOffresBundle:Contrat:delete
    requirements:
        id: \d+        